// @ts-check

// /**
//  * Creating a sidebar enables you to:
//  - create an ordered group of docs
//  - render a sidebar for each doc of that group
//  - provide next/previous navigation

//  The sidebars can be generated from the filesystem, or explicitly defined here.

//  Create as many sidebars as you want.

//  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
//  */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
// };

// export default sidebars;

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  docs: [
    'index',
    {
      type: 'category',
      label: 'Введение',
      items: [
        'introduction/index',
        'introduction/stakeholders',
        'introduction/scope',
      ],
    },
    {
      type: 'category',
      label: 'Требования',
      items: [
        'requirements/functional',
        'requirements/non-functional',
        'requirements/stakeholders'
      ],
    },
    {
      type: 'category',
      label: 'Архитектура',
      items: [
        'architecture/arch',
        'architecture/data-model',
        'architecture/integrations',
        'architecture/route-generation-process'
      ],
    },
    {
      type: 'category',
      label: 'API',
      items: [
        'api/index',
        'api/api-reference',
        'api/websocket',
      ],
    },
    {
      type: 'category',
      label: 'UI',
      items: [
        'ui-wireframes/wireframes',
      ],
    },
    {
      type: 'category',
      label: 'Стратегия',
      items: [
        'strategy/platformization',
      ],
    },
  ],
};